---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyloadng
  namespace: {{ .Release.Namespace }}
  labels:
    app: pyloadng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyloadng
  template:
    metadata:
      labels:
        app: pyloadng
    spec:
      volumes:
        - name: config
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.userspace.appData }}/pyload/config
        - name: downloads
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.userspace.userData }}/Downloads/pyload
        - name: passwords
          hostPath:
            type: FileOrCreate
            path: {{ .Values.userspace.appData }}/pyload/config/data/passwords.txt
#      serviceAccountName: default
#      automountServiceAccountToken: true
#      dnsPolicy: ClusterFirst
#      enableServiceLinks: true
      containers:
      - env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: TZ
          value: UTC
        name: pyloadng
        image: "lscr.io/linuxserver/pyload-ng:0.5.0"
        resources:
          requests:
            cpu: 25m
            memory: 400Mi
          limits:
            cpu: 500m
            memory: 1500Mi # extractions
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: downloads
        - name: passwords
          mountPath: /app/config/data/passwords.txt
        securityContext:
          runAsUser: 0

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: sys.bytetrade.io/v1alpha1
kind: ProviderRegistry
metadata:
  name: legacy-{{ .Release.Name }}
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  dataType: legacy_{{ .Release.Name }}
  deployment: {{ .Release.Name }}
  description: {{ .Release.Name }} legacy api v2
  endpoint: {{ .Release.Name }}-svc.{{ .Release.Namespace }}:5800
  group: api.{{ .Release.Name }}
  kind: provider
  namespace: {{ .Release.Namespace }}
  version: v2
  opApis:
  - name: All
    uri: /  
status:
  state: active
